# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SpotGlove_pb2 as SpotGlove__pb2


class CommandSpotStub(object):
    """The CommandSpot definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command = channel.unary_unary(
                '/SpotGlove.CommandSpot/Command',
                request_serializer=SpotGlove__pb2.CommandRequest.SerializeToString,
                response_deserializer=SpotGlove__pb2.CommandReply.FromString,
                )


class CommandSpotServicer(object):
    """The CommandSpot definition
    """

    def Command(self, request, context):
        """Commands Spot to do something
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandSpotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=SpotGlove__pb2.CommandRequest.FromString,
                    response_serializer=SpotGlove__pb2.CommandReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpotGlove.CommandSpot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommandSpot(object):
    """The CommandSpot definition
    """

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SpotGlove.CommandSpot/Command',
            SpotGlove__pb2.CommandRequest.SerializeToString,
            SpotGlove__pb2.CommandReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
